"""
fabric/approval_tool.py — THE shared approval-and-escalation workflow.

This is the concrete embodiment of "shared approval-and-escalation
workflow" and "unified audit & explainability log" from the Agent Fabric
architecture. Both finance_agent.py and procurement_agent.py call these
two functions identically — this file must never contain agent-specific
branching (no "if agent_name == 'finance_agent'" anywhere below).

Do not edit this file's function signatures once Phase 3 (finance_agent)
starts depending on it. If a later agent seems to need a signature
change, that's a signal the design has a problem — not a normal part of
adding an agent.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"
AUDIT_LOG_FILE = DATA_DIR / "audit_log.json"
ESCALATION_QUEUE_FILE = DATA_DIR / "escalation_queue.json"

_review_ticket_counter = 0


def _read_json_list(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with open(path, "r", encoding="utf-8") as f:
        content = f.read().strip()
        if not content:
            return []
        return json.loads(content)


def _write_json_list(path: Path, records: list[dict]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2)


def log_decision(
    agent_name: str,
    entity_type: str,
    entity_id: str,
    decision: str,
    reason: str,
    amount_eur: float | None = None,
) -> dict:
    """
    Appends a structured record to data/audit_log.json (created if absent).
    This is the ONLY function either agent uses to record outcomes — no
    agent-specific logging logic anywhere else in the codebase.
    """
    record = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "agent_name": agent_name,
        "entity_type": entity_type,
        "entity_id": entity_id,
        "decision": decision,
        "reason": reason,
        "amount_eur": amount_eur,
    }

    records = _read_json_list(AUDIT_LOG_FILE)
    records.append(record)
    _write_json_list(AUDIT_LOG_FILE, records)

    return record


def request_human_review(
    agent_name: str,
    entity_type: str,
    entity_id: str,
    reason: str,
) -> dict:
    """
    Appends to data/escalation_queue.json, representing the GCC review
    queue. Called by BOTH agents identically when they escalate.
    Returns a confirmation dict with a mock review_ticket_id and
    status="pending_review".
    """
    global _review_ticket_counter
    _review_ticket_counter += 1

    ticket = {
        "review_ticket_id": f"GCC-{7000 + _review_ticket_counter}",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "agent_name": agent_name,
        "entity_type": entity_type,
        "entity_id": entity_id,
        "reason": reason,
        "status": "pending_review",
    }

    tickets = _read_json_list(ESCALATION_QUEUE_FILE)
    tickets.append(ticket)
    _write_json_list(ESCALATION_QUEUE_FILE, tickets)

    return ticket
